Class {
	#name : 'MbDAccCompIeqcJeqcO',
	#superclass : 'MbDAccCompIeqcJecO',
	#instVars : [
		'paIeJeOipEJ',
		'paIeJeOipXdotJ',
		'paIeJeOipEdotJ'
	],
	#category : 'StCAD-MbD-MbDKinematicIJ',
	#package : 'StCAD-MbD',
	#tag : 'MbDKinematicIJ'
}

{ #category : 'VisualWorks metadata' }
MbDAccCompIeqcJeqcO class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
		'superclassNamespace' 'StCAD.MbD'
	)

]
