Class {
	#name : 'MbDAccCompIecJecOKec',
	#superclass : 'MbDKinematicDDotIeJe',
	#instVars : [
		'efrmK',
		'axisK',
		'viIeJeOKe',
		'aAjOKe',
		'vIeJeO'
	],
	#category : 'StCAD-MbD-MbDKinematicIJ',
	#package : 'StCAD-MbD',
	#tag : 'MbDKinematicIJ'
}

{ #category : 'VisualWorks metadata' }
MbDAccCompIecJecOKec class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
		'superclassNamespace' 'StCAD.MbD'
	)

]
