Class {
	#name : 'MbDAccCompIeqcJecOKeqc',
	#superclass : 'MbDAccCompIecJecOKeqc',
	#instVars : [
		'paiIeJeOKepEI',
		'paiIeJeOKepXdotI',
		'paiIeJeOKepEdotI'
	],
	#category : 'StCAD-MbD-MbDKinematicIJ',
	#package : 'StCAD-MbD',
	#tag : 'MbDKinematicIJ'
}

{ #category : 'VisualWorks metadata' }
MbDAccCompIeqcJecOKeqc class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
		'superclassNamespace' 'StCAD.MbD'
	)

]
