Class {
	#name : 'MbDAccCompIeqcJecO',
	#superclass : 'MbDAccCompIecJecO',
	#instVars : [
		'paIeJeOipEI',
		'paIeJeOipXdotI',
		'paIeJeOipEdotI'
	],
	#category : 'StCAD-MbD-MbDKinematicIJ',
	#package : 'StCAD-MbD',
	#tag : 'MbDKinematicIJ'
}

{ #category : 'VisualWorks metadata' }
MbDAccCompIeqcJecO class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
		'superclassNamespace' 'StCAD.MbD'
	)

]
