Class {
	#name : 'MbDAccCompIeqcJeqcOKeqc',
	#superclass : 'MbDAccCompIeqcJecOKeqc',
	#instVars : [
		'paiIeJeOKepEJ',
		'paiIeJeOKepXdotJ',
		'paiIeJeOKepEdotJ'
	],
	#category : 'StCAD-MbD-MbDKinematicIJ',
	#package : 'StCAD-MbD',
	#tag : 'MbDKinematicIJ'
}

{ #category : 'VisualWorks metadata' }
MbDAccCompIeqcJeqcOKeqc class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
		'superclassNamespace' 'StCAD.MbD'
	)

]
