Class {
	#name : 'MbDDistIeqctJeqc',
	#superclass : 'MbDDistIeqcJeqc',
	#instVars : [
		'prIeJept',
		'pprIeJepXIpt',
		'pprIeJepEIpt',
		'pprIeJepXJpt',
		'pprIeJepEJpt',
		'pprIeJeptpt'
	],
	#category : 'StCAD-MbD-MbDKinematicIJ',
	#package : 'StCAD-MbD',
	#tag : 'MbDKinematicIJ'
}

{ #category : 'VisualWorks metadata' }
MbDDistIeqctJeqc class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
		'superclassNamespace' 'StCAD.MbD'
	)

]
