Class {
	#name : 'MbDTime',
	#superclass : 'StMTime',
	#category : 'StCAD-MbD-MbDBasic',
	#package : 'StCAD-MbD',
	#tag : 'MbDBasic'
}

{ #category : 'VisualWorks metadata' }
MbDTime class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
		'superclassNamespace' 'StCAD.Math'
	)

]

{ #category : 'accessing' }
MbDTime >> fillJointForces: orderedCollection [ 
	"Do nothing."
]

{ #category : 'accessing' }
MbDTime >> fillJointTorques: orderedCollection [ 
	"Do nothing."
]

{ #category : 'accessing' }
MbDTime >> fillKineIJs: orderedCollection [ 
	"Do nothing."
]

{ #category : 'accessing' }
MbDTime >> fillKinedotIJs: orderedCollection [ 
	"Do nothing."
]
